[package]
name = "petstore-hyper"
version = "1.0.0"
authors = ["OpenAPI Generator team and contributors"]

[dependencies]
serde = "1.0.106"
serde_derive = "1.0.106"
serde_json = "1.0.51"
url = "2.1.1"
hyper = {version = "0.13.4", features = ["stream"], default-features = false}
base64 = "0.12.0"
futures = "0.3.4"
http = "0.2.1"

